### ISSUE TITLE
[HTTPS] What about HPKP?

### ISSUE THREAD

**Issue by rugk** [enko/datenknoten.me#1]
I saw you you support DANE which is crazily fantastic, but nevertheless it would also be nice if you could enable HTTP Public Key Pinning. A good guide to do this you can for example find here: https://noncombatant.org/2015/05/01/about-http-public-key-pinning/

(it's just that not many people/browser are using DANE...)

**Comment by enko** [comment]
Will do that this afternoon! Thanks for bringing it to my attention!

**Comment by rugk** [comment]
Just a small reminder.. :smile: ([HPKP is still not supported](https://www.ssllabs.com/ssltest/analyze.html?d=datenknoten.me))
And BTW here German instructions for HPKP: https://blog.pregos.info/2015/02/23/http-public-key-pinning-hpkp-erklaerung-und-einrichtung/

Please also notice issue #2...

**Comment by enko** [comment]
Added :+1:

**Comment by enko** [comment]
or not,  I think I need to create a backup pin.

**Comment by enko** [comment]
Created a backup pin and now firefox does not complains any more about about an illegal pinning entry.
