### ISSUE TITLE
[HTTPS] HSTS issues with diaspora* pot

### ISSUE THREAD

**Issue by rugk** [enko/datenknoten.me#2]
On your diaspora\* pot you're having HSTS problems.
Firefox reports: "Diese Website hat eine ungültige Strict-Transport-Security-Kopfzeile angegeben. [[Weitere Informationen]](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security)"

And yes it seems to be indeed wrong:

> Strict-Transport-Security:  "max-age=31536000, max-age=15768000"

Two expiration dates?

**Comment by rugk** [comment]
Okay, it seems you fixed it. New header:

> Strict-Transport-Security: "max-age=31536000"

**Comment by enko** [comment]
The problem was, that diaspora sets its own HTST header and i added a second via nginx and thous the header got 2 values.
